src/Entity/Place.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlaceRepository")
 */
class Place
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $star;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $fax;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="places")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $detail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="place")
     */
    private $images;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $userid;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getStar(): ?int
    {
        return $this->star;
    }

    public function setStar(?int $star): self
    {
        $this->star = $star;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setPlace($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getPlace() === $this) {
                $image->setPlace(null);
            }
        }

        return $this;
    }

    public function getUserid(): ?int
    {
        return $this->userid;
    }

    public function setUserid(?int $userid): self
    {
        $this->userid = $userid;

        return $this;
    }
}

src/Controller/Admin/PlaceController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Place;
use App\Form\PlaceType;
use App\Repository\PlaceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/place")
 */
class PlaceController extends AbstractController
{
    /**
     * @Route("/", name="admin_place_index", methods={"GET"})
     */
    public function index(PlaceRepository $placeRepository): Response
    {
        $places=$placeRepository->getAllPlaces();
        return $this->render('admin/place/index.html.twig', [
            'places' => $places,
        ]);
    }

    /**
     * @Route("/new", name="admin_place_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $place = new Place();
        $form = $this->createForm(PlaceType::class, $place);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            /** @var file $file */
            $file = $form['image']->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($file) {
                $fileName = $this->genareteUniqueFileName() . '.'. $file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName

                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'filename' property to store the PDF file name
                // instead of its contents
                $place->setImage($fileName);
            }
            //************file end upload **********
            $entityManager->persist($place);
            $entityManager->flush();

            return $this->redirectToRoute('admin_place_index');
        }

        return $this->render('admin/place/new.html.twig', [
            'place' => $place,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_place_show", methods={"GET"})
     */
    public function show(Place $place): Response
    {
        return $this->render('admin/place/show.html.twig', [
            'place' => $place,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_place_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Place $place): Response
    {
        $form = $this->createForm(PlaceType::class, $place);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //************file upload **********
            /** @var file $file */
            $file = $form['image']->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($file) {
                $fileName = $this->genareteUniqueFileName().'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName

                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'filename' property to store the PDF file name
                // instead of its contents
                $place->setImage($fileName);
            }
            //************file end upload **********
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_place_index');
        }

        return $this->render('admin/place/edit.html.twig', [
            'place' => $place,
            'form' => $form->createView(),
        ]);
    }
    /*
     * @return string
      */
    private function genareteUniqueFileName(){
        return md5(uniqid());
    }


    /**
     * @Route("/{id}", name="admin_place_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Place $place): Response
    {
        if ($this->isCsrfTokenValid('delete'.$place->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($place);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_place_index');
    }

}

src/Controller/PlaceController.php
<?php

namespace App\Controller;

use App\Entity\Place;
use App\Form\Place1Type;
use App\Form\PlaceType;
use App\Repository\PlaceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/places")
 */
class PlaceController extends AbstractController
{
    /**
     * @Route("/", name="user_place_index", methods={"GET"})
     */
    public function index(PlaceRepository $placeRepository): Response
    {
        $user=$this->getUser(); //get Login user data


        return $this->render('place/index.html.twig', [
            'places' => $placeRepository->findBy(['userid'=>$user->getId()]),
        ]);
    }

    /**
     * @Route("/new", name="user_place_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $place = new Place();
        $form = $this->createForm(Place1Type::class, $place);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            /** @var file $file */
            $file = $form['image']->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($file) {
                $fileName = $this->genareteUniqueFileName() . '.'. $file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName

                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'filename' property to store the PDF file name
                // instead of its contents
                $place->setImage($fileName);
            }
            //************file end upload **********

            $user=$this->getUser(); //get Login user data
            $place->setUserid($user->getId());
            $place->setStatus('New');


            $entityManager->persist($place);
            $entityManager->flush();

            return $this->redirectToRoute('user_place_index');
        }

        return $this->render('place/new.html.twig', [
            'place' => $place,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_place_show", methods={"GET"})
     */
    public function show(Place $place): Response
    {
        return $this->render('place/show.html.twig', [
            'place' => $place,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_place_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Place $place): Response
    {
        $form = $this->createForm(Place1Type::class, $place);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var file $file */
            $file = $form['image']->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($file) {
                $fileName = $this->genareteUniqueFileName() . '.'. $file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName

                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'filename' property to store the PDF file name
                // instead of its contents
                $place->setImage($fileName);
            }
            //************file end upload **********

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_place_index');
        }

        return $this->render('place/edit.html.twig', [
            'place' => $place,
            'form' => $form->createView(),
        ]);
    }

    /*
     * @return string
      */
    private function genareteUniqueFileName(){
        return md5(uniqid());
    }


    /**
     * @Route("/{id}", name="user_place_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Place $place): Response
    {
        if ($this->isCsrfTokenValid('delete'.$place->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($place);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_place_index');
    }
}

templates/place/_delete_form.html.twig
<form method="post" action="{{ path('user_place_delete', {'id': place.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ place.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/place/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/place/index.html.twig
{% extends 'homebase.html.twig' %}

            {% block title %}{{app.user.name }} Profile{% endblock %}

            {% block body %}
                <SCRIPT language="JavaScript" type="text/javascript">
                    function openWin(windowUrl,windowName,windowFeatures) { window.open(windowUrl,windowName,windowFeatures);}
                </SCRIPT>
                {{  include('user/usermenu.html.twig')}}
                <div class="container">
                    <div class="row profile">
                        <div class="col-md-3">
                            <div class="profile-sidebar">
                                <!-- SIDEBAR USERPIC -->
                                <div class="profile-userpic">
                                    <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg"
                                         class="img-responsive" alt="">
                                </div>
                                <!-- END SIDEBAR USERPIC -->
                                <!-- SIDEBAR USER TITLE -->
                                <div class="profile-usertitle">
                                    <img src="{{ asset('uploads/images/'~ app.user.image) }}" height="80px">
                                    <div class="profile-usertitle-name">
                                        {{ app.user.name }} {{ app.user.surname }}
                                    </div>

                                </div>
                                <!-- END SIDEBAR USER TITLE -->
                                <!-- SIDEBAR BUTTONS -->
                                <div class="profile-userbuttons">
                                    <button type="button" class="btn btn-success btn-sm">Follow</button>
                                    <button type="button" class="btn btn-danger btn-sm">Message</button>
                                </div>
                                <!-- END SIDEBAR BUTTONS -->
                                <!-- SIDEBAR MENU -->
                                <div class="profile-usermenu">
                                    <ul class="nav">
                                        <li>
                                            <a href="/user/">
                                                <i class="glyphicon glyphicon-user"></i>
                                                My Profile </a>
                                        </li>
                                        <li>
                                            <a href="/user/places">
                                                <i class="glyphicon glyphicon-home"></i>
                                                My Places </a>
                                        </li>
                                        <li>
                                            <a href="/user/comments">
                                                <i class="glyphicon glyphicon-comment"></i>
                                                My Comments</a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="glyphicon glyphicon-flag"></i>
                                                Contact </a>
                                        </li>
                                        <li>
                                            <a href="/logout">
                                                <i class="glyphicon glyphicon-log-out"></i>
                                                Logout </a>
                                        </li>
                                    </ul>
                                </div>
                                <!-- END MENU -->
                            </div>
                        </div>
                        <div class="col-md-9">


                            <h1>User Place List</h1>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            {#<th>Keywords</th>
            <th>Description</th>#}
            <th>Image</th>
            <th>Star</th>
            <th>Adress</th>
            {#<th>Phone</th>#}
            {#<th>Fax</th>#}
            <th>Email</th>
            <th>City</th>
            <th>Country</th>
            <th>I.Galery</th>
            {#<th>Location</th>#}
            <th>Status</th>
            {#<th>Created_at</th>
            <th>Updated_at</th>#}
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for place in places %}
            <tr>
                <td>{{ place.id }}</td>
                <td>{{ place.title }}</td>
                {#<td>{{ place.keywords }}</td>
                <td>{{ place.description }}</td>#}
                <td><img src="{{ asset('uploads/images/'~ place.image) }}" height="20"></td>
                <td>{{ place.star }}</td>
                <td>{{ place.adress }}</td>
                {#<td>{{ place.phone }}</td>#}
                {#<td>{{ place.fax }}</td>#}
                <td>{{ place.email }}</td>
                <td>{{ place.city }}</td>
                <td>{{ place.country }}</td>
                <td><a href="javascript:openWin('{{ path('user_image_new',{'id':place.id}) }}','','toolbar=no,location=no,directories=0,status=no,top=50,left=100,menuBar=no,scrollBars=yes,resizable=no,width=900,height=600');">
                        <img src="{{ asset('assets/admin/img') }}/gallery.png" height="30">
                    </a> </td>
                {#<td>{{ place.location }}</td>#}
                <td>{{ place.status }}</td>
                {#<td>{{ place.createdAt ? place.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ place.updatedAt ? place.updatedAt|date('Y-m-d H:i:s') : '' }}</td>#}
                <td>
                    <a href="{{ path('user_place_show', {'id': place.id}) }}" class="btn btn-primary">Göster</a>
                    <a href="{{ path('user_place_edit', {'id': place.id}) }}" class="btn btn-danger">Düzenle</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="17">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

                <a href="{{ path('user_place_new') }}" class="btn btn-success">Create new</a>



        </div>
    </div>
</div>

    <br>
    <br>

{% endblock %}

templates/place/show.html.twig
{% extends 'homebase.html.twig' %}

            {% block title %}{{app.user.name }} Profile{% endblock %}

            {% block body %}
                {{  include('user/usermenu.html.twig')}}
<div class="container">
    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg"
                         class="img-responsive" alt="">
                </div>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <img src="{{ asset('uploads/images/'~ app.user.image) }}" height="80px">
                    <div class="profile-usertitle-name">
                        {{ app.user.name }} {{ app.user.surname }}
                    </div>

                </div>
                <!-- END SIDEBAR USER TITLE -->
                <!-- SIDEBAR BUTTONS -->
                <div class="profile-userbuttons">
                    <button type="button" class="btn btn-success btn-sm">Follow</button>
                    <button type="button" class="btn btn-danger btn-sm">Message</button>
                </div>
                <!-- END SIDEBAR BUTTONS -->
                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                    <ul class="nav">
                        <li>
                            <a href="/user/">
                                <i class="glyphicon glyphicon-user"></i>
                                My Profile </a>
                        </li>
                        <li>
                            <a href="/user/places">
                                <i class="glyphicon glyphicon-home"></i>
                                My Places </a>
                        </li>
                        <li>
                            <a href="/user/comments">
                                <i class="glyphicon glyphicon-comment"></i>
                                My Comments</a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-flag"></i>
                                Contact </a>
                        </li>
                        <li>
                            <a href="/logout">
                                <i class="glyphicon glyphicon-log-out"></i>
                                Logout </a>
                        </li>
                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>
        <div class="col-md-9">


            <h1>User Place List</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ place.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ place.title }}</td>
            </tr>
            <tr>
                <th>Keywords</th>
                <td>{{ place.keywords }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ place.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td><img src="{{ asset('uploads/images/'~ place.image) }}" ></td>
            </tr>
            <tr>
                <th>Star</th>
                <td>{{ place.star }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ place.adress }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ place.phone }}</td>
            </tr>
            <tr>
                <th>Fax</th>
                <td>{{ place.fax }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ place.email }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ place.city }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ place.country }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ place.location }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ place.status }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ place.createdAt ? place.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ place.updatedAt ? place.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Detail</th>
                <td>{{ place.detail | raw}}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('user_place_index') }}" class="btn btn-primary">back to list</a>

    <a href="{{ path('user_place_edit', {'id': place.id}) }}" class="btn btn-success">edit</a>

    {{ include('place/_delete_form.html.twig') }}

        </div>
    </div>
</div>

                <br>
                <br>
{% endblock %}